[package]
name = "replayman"
version = "0.1.0"

authors = ["Sho Nakatani <lay.sakura@gmail.com>"]
license = "MIT OR Apache-2.0"

edition = "2021"

[dependencies]
springql-foreign-service = "0.1"

chrono = "0.4"

anyhow = "1.0"

clap = "3.0.0-beta.5"
